Shots and feature map exposure
pyRiemann/pyRiemann-qiskit pull request #14
Opened 2021-11-19 19:16 UTC by gcattan

Expose the number of shots and the feature map (part of issue #13)

2021-11-21 23:08 UTC, sylvchev approved these changes
Nice work!

2021-11-22 21:01 UTC, qbarthelemy requested changes
LGTM! Only minor comments.

2021-11-23 09:14 UTC, gcattan commented on pyriemann_qiskit/utils/hyper_params_factory.py
> +    entanglement : Union[str, List[List[int]], Callable[[int], List[int]]]
This is a union between a string and list of indices. I have now improved the description.

2021-11-23 09:16 UTC, gcattan commented on pyriemann_qiskit/utils/hyper_params_factory.py
> +        The number of repeated circuits, has a min. value of 1.
I wanted to say that the value has to be greater or equal to 1. 
I have now updated the description to put it more clear.

2021-11-23 19:47 UTC, gcattan commented
Thank you for the comments. There is still some problem with the pipeline. I should investigate it deeper, but it seems that `git` failed to be installed on the doc pipeline. If you have an idea do not hesitate :)

2021-11-23 21:44 UTC, qbarthelemy requested changes
Again, some minor remarks.

More generally:

1 - don't merge master in your branch, but **rebase** your branch on master; otherwise, it is really difficult to understand if modifications com from branch and from master.

2 - to easily update your fork master on the pyRiemann-qiskit master, do:
`git remote add upstream https://github.com/pyriemann/pyriemann-qiskit.git`
Then, before creating a branch, pull from `upstream`.

See SciPy guidelines: https://docs.scipy.org/doc/scipy/reference/dev/contributor/development_workflow.html

2021-11-23 21:50 UTC, qbarthelemy commented
> There is still some problem with the pipeline. I should investigate it deeper, but it seems that git failed to be installed on the doc pipeline. If you have an idea do not hesitate :)

I think that the problem comes from module `datasets` of pyRiemann, not declared in init file. Its import fails. This should be corrected after merge of
https://github.com/pyRiemann/pyRiemann/pull/149/commits/91c62e1c6d2c7ad789c186c65ca39a769d33016f
@sylvchev

2021-11-24 18:57 UTC, gcattan commented on pyriemann_qiskit/utils/hyper_params_factory.py
> +def gen_zz_feature_map(reps=2, entanglement='linear'):
Thanks! I added a couple of tests and removed the `pairwise` option which was not available in this version.

2021-11-24 21:36 UTC, qbarthelemy requested changes
Great job!
Last comments, then it will be ok for me.

2021-11-24 21:36 UTC, qbarthelemy commented on tests/test_utils_hyper_params_factory.py
> +        pass
To test if a function raises an error, you can use:
```
with pytest.raises(ValueError):
    my_function.do_a_stuff_raising_an_error()
```

2021-11-24 21:36 UTC, qbarthelemy commented on tests/conftest.py
> +def _get_linear_entanglement(n_qbits_in_block, feature_dim):
For consistency in notations, you should use `n_features` instead of `feature_dim`.

2021-11-25 09:37 UTC, gcattan commented
Thank you for the useful comments! There is still some CI/CD error. I will wait for the aforementioned commit to be merged and come back to this if required :)

2021-11-25 11:43 UTC, qbarthelemy approved these changes
Thx @gcattan !

2021-11-25 22:06 UTC, merged