Exposure of Gamma, optimizer and variational form
pyRiemann/pyRiemann-qiskit pull request #16
Opened 2021-11-30 20:38 UTC by gcattan

https://github.com/pyRiemann/pyRiemann-qiskit/issues/13

2021-12-01 15:29 UTC, qbarthelemy requested changes
Good job! Don't hesitate to have a look to new tests of pyRiemann, to write your tests with a systematic checking of all parameters and functions.

2021-12-01 15:29 UTC, qbarthelemy commented on pyriemann_qiskit/classification.py
> +    ----------
```suggestion
    Parameters
    ----------
```

2021-12-01 15:29 UTC, qbarthelemy commented on pyriemann_qiskit/classification.py
> +    .. [3] Available from: \
```suggestion
           doi: 10.1038/s41586-019-0980-2.
 
    .. [3] Available from: \
```

2021-12-01 15:29 UTC, qbarthelemy commented on pyriemann_qiskit/classification.py
> +    Attributes
`optimizer` and `gen_var_form` are parameters since they are defined in init.
```suggestion
    Parameters
```

2021-12-01 15:29 UTC, qbarthelemy commented on pyriemann_qiskit/classification.py
> +        https://qiskit.org/documentation/stable/0.19/stubs/qiskit.aqua.algorithms.VQC.html?highlight=vqc#qiskit.aqua.algorithms.VQC
```suggestion
        https://qiskit.org/documentation/stable/0.19/stubs/qiskit.aqua.algorithms.VQC.html
```

2021-12-01 15:29 UTC, qbarthelemy commented on pyriemann_qiskit/utils/hyper_params_factory.py
> +    For more details, see [3] and [4].
```suggestion
    For more details, see [3]_ and [4]_.
```

2021-12-01 15:29 UTC, qbarthelemy commented on pyriemann_qiskit/utils/hyper_params_factory.py
> +        See [3] for implementation details.
```suggestion
        See [3]_ for implementation details.
```

2021-12-01 19:42 UTC, gcattan commented
Thank you for the feedback and the suggestions! 
I have tried to apply `@pytest.mark.parametrize` as much as possible and I plan to come back to `test_classification.py` when I will be working on #11.
But I can of course address some of the refactorings here if you would prefer.

2021-12-03 08:45 UTC, sylvchev approved these changes

2021-12-03 08:46 UTC, sylvchev commented
Good for me!
We could merge this and you could update `test_classification.py` in next PR. Ok for you?

2021-12-03 10:27 UTC, gcattan commented
Ok for me :)

2021-12-03 19:11 UTC, qbarthelemy approved these changes
Ok to update test_classification.py in a next PR.

2021-12-03 19:12 UTC, merged

2021-12-03 19:12 UTC, qbarthelemy commented
Thx @gcattan

2021-12-03 19:31 UTC, gcattan commented
Thank you both for the time reviewing the PRs :)