Introduce prepare_data in conftest
pyRiemann/pyRiemann-qiskit pull request #18
Opened 2022-01-04 12:59 UTC by gcattan

As a first step to https://github.com/pyRiemann/pyRiemann-qiskit/issues/11, this PR introduces a `prepare_data` method to generate random or expected features and labels.

2022-01-04 19:49 UTC, qbarthelemy requested changes

2022-01-05 17:31 UTC, qbarthelemy approved these changes

2022-01-05 17:31 UTC, merged

2022-01-05 17:31 UTC, qbarthelemy commented
Thx @gcattan !

2022-01-05 18:44 UTC, gcattan commented
Thanks for the review :)