Feat/mdm predict distances
pyRiemann/pyRiemann-qiskit pull request #248
Opened 2024-02-29 18:26 UTC by gcattan

2024-02-29 18:29 UTC, gcattan commented on pyriemann_qiskit/pipelines.py
>          clf_mean_logeuclid_dist_cpm = QuantumMDMWithRiemannianPipeline(
This VotingClassifier should be replaced by a voting classifier Q-MDM/NHC or Q-MDM/MDM

2024-02-29 18:30 UTC, gcattan commented on pyriemann_qiskit/utils/distance.py
> +    weights = optimizer.solve(prob, reshape=False)
This is pretty basic. We can think of someting clever in the future.

2024-02-29 19:37 UTC, toncho11 commented
Can you please put a more detailed description of the PR.

2024-03-01 12:09 UTC, qbarthelemy requested changes

2024-03-01 12:09 UTC, qbarthelemy commented on pyriemann_qiskit/utils/distance.py
> +    [2]_.
```suggestion
    Weights for Log-Euclidean distance between a SPD matrix B and the convex hull of a set
    of SPD matrices A [1]_, formulated as a Constraint Programming Model (CPM)
    [2]_.
```

2024-03-01 12:09 UTC, qbarthelemy commented on pyriemann_qiskit/utils/distance.py
>          it returns the optimized weights for the set of SPD matrices A.
```suggestion
        Optimized weights for the set of SPD matrices A.
```

2024-03-01 12:51 UTC, gcattan commented on pyriemann_qiskit/classification.py
> +from pyriemann_qiskit.utils.distance import distance_functions, is_cpm_dist
Hm. Yes, but I will need to move `is_qmean` too, but it is also used in the `pipeline` module.

2024-03-01 15:29 UTC, qbarthelemy commented on pyriemann_qiskit/classification.py
> +from pyriemann_qiskit.utils.distance import distance_functions, is_cpm_dist
We should merge `is_qdist` and `is_qmean` into a generic `is_qfunction`.

2024-03-01 15:42 UTC, gcattan commented on pyriemann_qiskit/classification.py
> +from pyriemann_qiskit.utils.distance import distance_functions, is_cpm_dist
Ok. Let's create a new module `utils/utils.py`?

2024-03-04 12:03 UTC, qbarthelemy requested changes

2024-03-04 20:46 UTC, qbarthelemy approved these changes
Thx @gcattan !
Last remark: don't forget to update whatsnew file.

2024-03-04 21:04 UTC, gcattan commented
Thx @qbarthelemy :)

Until now I was updating the whatsnew on each release only, based on the generated release notes. 
Do you mean to change this?

2024-03-05 03:27 UTC, qbarthelemy commented
> Do you mean to change this?

No, don't change anything.

2024-03-05 05:56 UTC, merged