Add Riemann Quantum Classifier
pyRiemann/pyRiemann-qiskit pull request #31
Opened 2022-02-04 20:30 UTC by gcattan

This PR implements #23.
The helper classifier which is implemented here will be used for CVGridSearch.
A couple of tests were added to `test_classification.py` and required to refactorize some of the methods into a dataset/utils module.

(WIP)

2022-02-07 08:05 UTC, qbarthelemy requested changes

2022-02-07 12:13 UTC, gcattan commented on pyriemann_qiskit/classification.py
> +class RiemannQuantumClassifier(BaseEstimator, ClassifierMixin,
I agree. I will try to find something more appropriate.

2022-02-07 16:16 UTC, gcattan commented
Thanks for the review!

There is still a problem with the pipeline, using python 3.8. To be honest I am not sure where it comes from.
Tests are ok on my local computer.

2022-02-07 19:51 UTC, gcattan commented
Ok, I compared the package version with older builds and it seems that the scipy version changed 2 days ago. 

@toncho11 FYI

2022-02-11 20:01 UTC, qbarthelemy approved these changes

2022-02-11 20:01 UTC, merged

2022-02-11 20:35 UTC, gcattan commented
Thanks for the review :)