Added an example that uses datasets from MOABB and the RG+QuantumSVM pipeline
pyRiemann/pyRiemann-qiskit pull request #39
Opened 2022-04-11 06:52 UTC by toncho11

The example visualizes and compares with two other "standard" pipelines. 
It depends on the newest version of MOABB 0.4.6.

2022-04-14 07:57 UTC, gcattan reviewed
Good job :) Can you in addition, add this example to `doc/index.rst`?

![image](https://user-images.githubusercontent.com/6229031/163340371-29d57df1-3998-4ef9-8818-c5ac56632fa0.png)

2022-04-14 07:57 UTC, gcattan commented on examples/ERP/classify_P300_bi.py
> +        return np.reshape(X, (X.shape[0], -1))
If we intend to reuse this, can you add it to `utils.filtering`?

2022-04-14 07:57 UTC, gcattan commented on examples/ERP/classify_P300_bi.py
> +    #q_account_token="" #IBM Quantum TOKEN
Can you raise a defect for the `q_account_token`, following your observations in our Skype conversation?

2022-04-14 07:57 UTC, gcattan commented on examples/ERP/classify_P300_bi.py
> +    LDA(solver="lsqr", shrinkage="auto")
You do not have the same number of component in your feature vector, as compared with the two other pipelines. Is this intended?

2022-04-14 07:57 UTC, gcattan commented on examples/ERP/classify_P300_bi.py
> +fig.show()
Can you post on a comment here the resulting figure?

2022-04-14 07:57 UTC, gcattan commented on examples/ERP/classify_P300_bi.py
> +
Add here `print(_doc_)`

2022-04-14 09:06 UTC, gcattan commented on examples/ERP/classify_P300_bi.py
> +standard pipelines.
Adapt here text according to our Skype conversation.

2022-04-14 09:06 UTC, gcattan commented on examples/ERP/classify_P300_bi.py
> +from sklearn import svm
Move this at the beginning.

2022-04-15 08:53 UTC, gcattan commented on examples/ERP/classify_P300_bi.py
> +        return np.reshape(X, (X.shape[0], -1))
Do we still need this since you changed your example?

2022-04-15 08:53 UTC, gcattan commented on examples/ERP/classify_P300_bi.py
> +    #q_account_token="" #IBM Quantum TOKEN
Follow-up opened here: https://github.com/pyRiemann/pyRiemann-qiskit/issues/40

2022-04-15 19:09 UTC, gcattan commented on doc/requirements.txt
> +moabb>=0.4.6
Looks like moabb is not compatible with Python 3.6.
We can try to install from the source as you suggested or drop support for python 3.6 and eventually add support for 3.9 (but qiskit-aer is not compatible with 3.9, so we can only support 3.9 after updating qiskit).

2022-04-15 19:21 UTC, gcattan commented on doc/requirements.txt
> +moabb>=0.4.6
Ok, so I tried installing from the source, but it fails with the same error.

2022-04-15 19:33 UTC, gcattan approved these changes

2022-04-17 09:33 UTC, sylvchev commented on doc/requirements.txt
> +moabb>=0.4.6
Yes, we dropped support of 3.6 when it was deprecated. You could move to python-3.7 for base requirement (support will end 27 Jun 2023).
Good idea to move moabb dependency to doc, no need to have it in the basic requirements.

2022-04-17 09:45 UTC, sylvchev requested changes

2022-04-17 09:45 UTC, sylvchev commented on examples/ERP/classify_P300_bi.py
> +ERP EEG decoding with Quantum Classifier.
You could change the title, as this is the same title than `plot_classify_EEG_quantum.py` and they should appears dfferently on the doc.

2022-04-17 09:45 UTC, sylvchev commented on examples/ERP/classify_P300_bi.py
> +fig.show()
```suggestion
plt.show()
```

The figure is not shown on the generated documentation, try using `plt.show()` to display the plot.

2022-04-17 12:35 UTC, gcattan commented on doc/requirements.txt
> +moabb>=0.4.6
Ok, I removed support for python-3.6, and opened issue #43 as a reminder to bring support for 3.9.

2022-04-19 19:56 UTC, toncho11 commented
Hi,

I think everything is ready for this PR to be accepted.

2022-04-20 16:59 UTC, qbarthelemy approved these changes

2022-04-30 12:27 UTC, gcattan commented
@sylvchev did you have a chance to review the last modification?

2022-05-14 10:38 UTC, gcattan commented
@sylvchev

2022-05-16 21:44 UTC, sylvchev approved these changes

2022-05-16 21:44 UTC, merged

2022-05-24 17:21 UTC, gcattan commented
@toncho11 thanks for taking care of this. Do you think we can reuse some elements of your presentation at `nbt-berlin` to improve our documentation?

2022-07-31 13:00 UTC, gcattan commented
I was wondering how can provides an estimate of the chance level for the bi2012 dataset. Is there something we can reuse from moabb @sylvchev ?